config/routes.rb
Rails.application.routes.draw do
  resources :rooms, only: [:index, :show] do
    member do
      get :ended
    end
  end

  root to: 'home#index'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user_room

  after_create_commit { MessageBroadcastJob.perform_later self }

  def user_id
    user_room.user_id
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :users, through: :user_rooms

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  def partner(querying_user)
    user_rooms.find_by('user_id != ?', querying_user).user
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_rooms, dependent: :destroy

  has_many :rooms, through: :user_rooms
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room

  has_many :messages, dependent: :destroy

  def partner_id
    UserRoom.find_by('room_id = ? AND id != ?', self.room_id, self.id).try(:user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end

  def authenticate
    unless User.exists?(id: cookies.signed[:user_id])
      user = User.create!(name: Naming.names.sample)

      cookies.signed[:user_id] = {
        value: user.id,
        expires: 1.hour.from_now
      }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    if available_room
      available_room.user_rooms.create(user: current_user)
      available_room.update(available: false)
      partner = available_room.partner(current_user)

      flash['notice'] = "チャットルームへ入室しました。<br>あたたは<b>#{current_user.name}</b>で相手は<b>#{partner.name}さん</b>です。"
      redirect_to room_path(available_room)
    else
      room = create_room

      flash['notice'] = "相手を待っています。あたたは<b>#{current_user.name}</b>です。"
      redirect_to room_path(room)
    end
  end

  def show
    @room = current_user.rooms.find_by(id: params[:id])
    redirect_to root_path and return unless @room

    @messages = Message.where(user_room_id: @room.user_room_ids).order(created_at: :asc)
  end

  def ended
    @room = current_user.rooms.find_by(id: params[:id])
    redirect_to root_path and return unless @room

    @messages = Message.where(user_room_id: @room.user_room_ids).order(created_at: :asc)
  end

  private

  def available_room
    @available_room ||= Room.joins(:user_rooms).where('user_rooms.user_id != ? AND rooms.available = ?', current_user, true).first
  end

  def create_room
    Room.create.tap do |room|
      room.user_rooms.create(user: current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%section
  .row
    .columns.medium-9.medium-centered.large-6.large-centered
      %h2.heading.margin-vertical
        見知らぬ誰かと
        %br
        チャットを楽しめる
        %br
        Webサービス。
      %p.subheading.text-small
        %span.text-primary
          「チャットを開始する」
        をクリックすると、
        同じようにクリックした誰か一人との
        チャットが開始します。
        チャットの内容は公開されません。
        見知らぬ誰かと何を話すかは皆さんの自由です。

      .start-chat-link-container
        = link_to fa_icon('commenting', text: 'チャットを開始する'), rooms_path, class: 'button large'

      .service-explanation
        .row
          .columns.medium-6
            .media-object
              .media-object-section
                = fa_icon('comments-o', class: 'icon large')
              .media-object-section
                %h5.heading.text-small
                  誰かと話したい！そんなときに
                %p.subheading.text-small
                  暇なとき、さみしいとき、相談したいとき、
                  HChatなら「チャットを開始する」ボタンを
                  クリックするとすぐに話し相手が見つかるよ！

          .columns.medium-6
            .media-object
              .media-object-section
                = fa_icon('heart', class: 'icon large')
              .media-object-section
                %h5.heading.text-small
                  見ず知らずの人と意気投合しちゃうかも!?
                %p.subheading.text-small
                  自分とは違う年代、性別、職業、地域、趣味の人
                  など普段の生活では知り合わないような人と
                  話せて盛り上がるかも！？

app/views/layouts/application.html.haml
!!! 5
%html{ lang: "en"}
  %head
    %meta{ charset: "utf-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ name: "description", content: "hchat" }

    %title= yield(:title).presence || 'hchat'

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = action_cable_meta_tag

  %body
    %header
      .row
        .columns.medium-9.medium-centered.large-6.large-centered
          .logo
            = link_to(fa_icon('heartbeat', text: 'HChat', class: 'js-logo'), root_path)
          .tagline
            1クリックで始まる無料チャットサイト

    .content-wrapper
      = yield
      .sticky-footer-push

app/views/messages/_message.html.haml
:ruby
  mine_or_not_mine = local_assigns[:user] && ((local_assigns[:user] == message.user_room.user) ? 'mine' : 'not-mine')

.message{ class: mine_or_not_mine }
  %span.body.rounded.message-tip
    = message.content

app/views/rooms/ended.html.haml
%section
  .row
    .columns.medium-9.medium-centered.large-6.large-centered
      .js-message-list.message-list
        = render @messages, user: current_user

      .form-container
        %form
          .input-group
            %input.input-group-field.chat-text-area{ type: "text", disabled: true }
            .input-group-button
              %button.button.secondary.chat-submit-button{ disabled: true }
                = fa_icon('commenting', text: '発信')

      = link_to fa_icon('refresh', text: '新規チャット'), rooms_path, class: 'button'

app/views/rooms/show.html.haml
%section
  .row
    .columns.medium-9.medium-centered.large-6.large-centered
      .js-joined-notification.joined-notification.callout.success.hide
      .js-left-notification.left-notification.callout.alert.hide

      - if flash[:notice]
        .flash-notice-container
          .callout.warning.js-flash-notice.flash-notice
            = raw(flash[:notice])

  .row
    .columns.medium-9.medium-centered.large-6.large-centered
      .js-message-list.message-list
        = render @messages, user: current_user

      .message.js-typing.typing.hide{ class: 'not-mine' }
        %span.body.rounded.message-tip
          = fa_icon('ellipsis-h', class: 'fa-pulse')

      .form-container
        %form
          .channel{ 'data-room-id' => @room.id, 'data-current-user-id' => current_user.id }

          .input-group
            %input.input-group-field.js-chat-text-area.chat-text-area{ type: "text" }
            .input-group-button
              %button.button.secondary.js-chat-submit-button.chat-submit-button
                = fa_icon('commenting', text: '発信')

      - has_partner = (@room.users.count > 1)
      - if has_partner
        = link_to fa_icon('times', text: 'チャット終了'), ended_room_path(@room), class: 'js-end-chat button gray'
        = link_to fa_icon('refresh', text: '新規チャット'), rooms_path, class: 'js-new-chat button hide'
      - else
        = link_to fa_icon('times', text: 'チャット終了'), ended_room_path(@room), class: 'js-end-chat button gray hide'
        = link_to fa_icon('refresh', text: '新規チャット'), rooms_path, class: 'js-new-chat button'